import logo from '../logo.svg';
import '../App.css';
import {Button, FormControl, FormControlLabel, FormLabel, Radio, RadioGroup} from "@mui/material";
import InfoDrawer from "./Drawer";
import {useLocation, useNavigate} from "react-router-dom";
import {useState} from "react";

const info = "Project Type is one of the root characteristics of a project, which points its nature. Usually project type is a high-level definition of a project that helps to identify methodologies to be suitable, objects and resources to be involved into the project, and nature of products to be generated by this project. When an organization operates a conception of project type, this may indicate that this organization possesses different templates for different project types – these templates package suitable elements and tools to plan, manage, and control every conventional type of projects. Projects are classified by the following categories (the major ones): "


export default function ExampleApplication() {
    const {state} = useLocation()
    const navigate = useNavigate()
    const [userState, setUserState] = useState({
        projectType: undefined,
        startDate: undefined,

    })

    const changeHandler = (e) => {
        setUserState(prevState => {
            return {...prevState, [e.target.name] : e.target.value}
        })
    }

    return (
        <div className="App">
            <FormControl>
                <FormLabel id="demo-radio-buttons-group-label">What kind of project-type describes your project best?</FormLabel>
                <RadioGroup
                    onChange={changeHandler}
                    aria-labelledby="demo-radio-buttons-group-label"
                    defaultValue="construction"
                    name="projectType"
                >
                    <FormControlLabel value="construction" control={<Radio />} label="Construction" />
                    <FormControlLabel value="transformation" control={<Radio />} label="Transformation" />
                    <FormControlLabel value="RD" control={<Radio />} label="Research and development" />
                </RadioGroup>
            </FormControl>
            <InfoDrawer
                info_text = {info}
            />
            <Button
                variant="contained"
                onClick={() => console.log(userState)}
            >
                Continue
            </Button>
            <Button
                variant="outlined"
                color={"secondary"}
                onClick={() => {
                    console.log(state)
                    navigate(state?.prevPage)
                }}
            >
                Back
            </Button>
        </div>
    );
}

