version: "3.9"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/opt/
    env_file:
      - ./environment/flask.env
    ports:
      - "5000:5000"
