version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    volumes:
      - ./src:/opt/
      - ./config.ini:/opt/config.ini
    env_file:
      - ./environment/flask.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./environment/postgres.env
      - ./environment/postgres_secret.env
    ports:
      - "6543:5432"

volumes:
  postgres-data:
